from shutit import shutit_module

class test14(shutit_module.ShutItModule):

	def build(self, shutit):
		shutit.send('''cp /etc/resolv.conf /tmp/b''')
		shutit.delete_text('''# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN''','/tmp/b')

		a = '''a
b
c
d
e
'''
		shutit.send_file('/tmp/a',a,user='daemon',group='daemon')
		shutit.pause_point('')
		md5sum1 = shutit.send_and_get_output('md5sum /tmp/a')
		shutit.add_line_to_file('e','/tmp/a')
		md5sum2 = shutit.send_and_get_output('md5sum /tmp/a')
		if md5sum1 != md5sum2:
			shutit.fail('file was changed 1') # pragma: no cover

		md5sum1 = shutit.send_and_get_output('md5sum /tmp/a')
		shutit.add_line_to_file("abc'def",'/tmp/a')
		md5sum2 = shutit.send_and_get_output('md5sum /tmp/a')
		if md5sum1 == md5sum2:
			shutit.fail('file was not changed 2') # pragma: no cover

		md5sum1 = shutit.send_and_get_output('md5sum /tmp/a')
		shutit.add_line_to_file("abc'def",'/tmp/a')
		md5sum2 = shutit.send_and_get_output('md5sum /tmp/a')
		if md5sum1 != md5sum2:
			shutit.fail('file was changed 3') # pragma: no cover

		md5sum1 = shutit.send_and_get_output('md5sum /tmp/a')
		shutit.delete_text("""a
""",'/tmp/a')
		md5sum2 = shutit.send_and_get_output('md5sum /tmp/a')
		if md5sum1 == md5sum2:
			shutit.fail('file was not changed 4') # pragma: no cover

		md5sum1 = shutit.send_and_get_output('md5sum /tmp/a')
		shutit.delete_text("""d
e""",'/tmp/a')
		md5sum2 = shutit.send_and_get_output('md5sum /tmp/a')
		if md5sum2 != 'd4ebec8d1b263504b76f0b5e88e27ce1  /tmp/a':
			shutit.fail('md5sum wrong 5') # pragma: no cover
		if md5sum1 == md5sum2:
			shutit.fail('file was not changed 5') # pragma: no cover
		return True

	def get_config(self, shutit):
		return True

	def test(self, shutit):
		# For test cycle part of the ShutIt build.
		return True

	def finalize(self, shutit):
		# Any cleanup required at the end.
		return True
	
	def is_installed(self, shutit):
		return False


def module():
	return test14(
		'test.test14.test14.test14', 1627321857.00293867346,
		description='',
		maintainer='',
		depends=['shutit.tk.setup']
	)

